#pragma once

// #define AUTO_SHIFT_TIMEOUT 180
// #define NO_AUTO_SHIFT_SPECIAL

#define SPLIT_LAYER_STATE_ENABLE
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD
#define QUICK_TAP_TERM 120
#define QUICK_TAP_TERM_PER_KEY
